version: "3"

services:
  ptolemaios:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - .:/ptolemaios
      - /ptolemaios/node_modules
    entrypoint:
      - yarn
      - dev